<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <SscSourceRoot Condition="'$(SscSourceRoot)' == ''">../../Sexslavecraft</SscSourceRoot>
    <EnableAnimationTestStub Condition="'$(EnableAnimationTestStub)' == ''">true</EnableAnimationTestStub>
    <DefineConstants Condition="'$(EnableAnimationTestStub)' == 'true'">$(DefineConstants);SSC_TEST_WITH_ANIMATIONS</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(SscSourceRoot)/common/RitualTrainingUtility.cs" Link="Production/RitualTrainingUtility.cs" />
  </ItemGroup>
</Project>
